console.group("Group1");
console.log("message1");
console.log("message2");
console.group("child Group");
console.log("message1");
console.log("message2");
console.group("Grand child Group");
console.log("message1");
console.log("message2");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.group("Group2");
console.log("message1");
console.log("message2");
console.groupEnd();